import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const interMono = Inter({
  variable: "--font-inter-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Medoc",
  description: "Medoc est une application web moderne conçue pour faciliter la recherche rapide et fiable de médicaments. Elle permet aux utilisateurs de consulter en quelques secondes les informations essentielles sur un médicament et de vérifier sa disponibilité. Grâce à une interface simple, fluide et intuitive, l’application aide professionnels de santé comme particuliers à accéder facilement aux données dont ils ont besoin.Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.variable} ${interMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
